local M = {}

function M.highlight(palette, opts)
  return {
    Normal = {
      fg = palette.fg,
      bg = opts.transparent and palette.none or palette.bg,
    },
    SignColumn = { bg = opts.transparent and palette.none or palette.bg },
    MsgArea = {
      fg = palette.fg,
      bg = opts.transparent and palette.none or palette.bg,
    },
    ModeMsg = { fg = palette.fg, bg = palette.bg },
    MsgSeparator = { fg = palette.fg, bg = palette.bg },
    SpellBad = { sp = palette.error, undercurl = true },
    SpellCap = { sp = palette.yellow, undercurl = true },
    SpellLocal = { sp = palette.sign_add, undercurl = true },
    SpellRare = { sp = palette.purple, undercurl = true },
    NormalNC = {
      fg = palette.fg,
      bg = opts.transparent and palette.none or palette.bg,
    },
    Pmenu = { fg = palette.light_gray, bg = palette.accent },
    PmenuSel = { bg = palette.purple_soft, fg = palette.bg, reverse = false },
    PmenuMatchSel = { bg = palette.purple_medium, fg = palette.bg, reverse = false },
    WildMenu = { fg = palette.blue, bg = palette.alt_bg },
    CursorLineNr = {
      fg = palette.yellow_soft or palette.light_gray,
      bold = true,
    },
    Comment = vim.tbl_extend(
      "force",
      { fg = palette.gray_dim or palette.medium_gray },
      opts.styles.comments
    ),
    Folded = { fg = palette.gray_warm or palette.light_gray, bg = palette.alt_bg },
    FoldColumn = { fg = palette.gray_warm or palette.light_gray, bg = palette.alt_bg },
    LineNr = { fg = palette.gray_dim or palette.medium_gray },
    Whitespace = { fg = palette.gray_dark or palette.gray },
    VertSplit = { fg = palette.bg, bg = palette.accent },
    CursorLine = {
      bg = palette.alt_bg,
    },
    CursorColumn = { bg = palette.alt_bg },
    ColorColumn = { bg = palette.alt_bg },
    NormalFloat = {
      bg = opts.transparent and palette.none or palette.alt_bg,
    },
    Visual = { bg = palette.gray },
    VisualNOS = { bg = palette.alt_bg },
    WarningMsg = { fg = palette.error, bg = palette.bg },
    DiffAdd = { bg = palette.accent_green },
    DiffText = { fg = palette.fg, bg = palette.accent_lighter_blue },
    Changed = {
      fg = palette.sign_change,
    },
    DiffChange = {
      fg = palette.sign_change,
      bg = palette.accent_blue,
    },
    DiffDelete = { fg = palette.sign_delete, bg = palette.accent_red },
    QuickFixLine = { bg = palette.accent },
    PmenuSbar = { bg = palette.alt_bg },
    PmenuThumb = { bg = palette.light_gray },
    MatchWord = { underline = true },
    MatchParen = vim.tbl_extend(
      "force",
      { fg = palette.blue, bg = palette.bg, underline = true },
      opts.styles.match_paren
    ),
    MatchWordCur = { underline = true },
    MatchParenCur = { underline = true },
    Cursor = { fg = palette.cursor_fg, bg = palette.cursor_bg },
    lCursor = { fg = palette.cursor_fg, bg = palette.cursor_bg },
    CursorIM = { fg = palette.cursor_fg, bg = palette.cursor_bg },
    TermCursor = {
      fg = palette.cursor_fg,
      bg = palette.cursor_bg,
      reverse = false,
    },
    TermCursorNC = {
      fg = palette.alt_bg,
      reverse = false,
    },
    Conceal = { fg = palette.fg },
    Directory = { fg = palette.blue },
    SpecialKey = { fg = palette.blue },
    Title = { fg = palette.blue },
    ErrorMsg = { fg = palette.error, bg = palette.bg, bold = true },
    Search = { fg = palette.orange, bg = palette.alt_bg },
    IncSearch = { fg = palette.alt_bg, bg = palette.yellow_gold or palette.orange },
    Substitute = { fg = palette.alt_bg, bg = palette.yellow_soft or palette.orange },
    MoreMsg = { fg = palette.yellow_soft or palette.cyan },
    Question = { fg = palette.yellow_soft or palette.cyan },
    EndOfBuffer = { fg = palette.gray },
    NonText = { fg = palette.fg },
    Variable = vim.tbl_extend("force", { fg = palette.orange_amber or palette.light_gray or palette.gray_warm or palette.fg }, opts.styles.variables),
    String = { fg = palette.orange_amber or palette.orange_copper or palette.orange_clay or palette.gray_warm or palette.purple_bright or palette.medium_gray_blue },
    Character = { fg = palette.purple_bright or palette.green },
    Constant = { fg = palette.fg },
    Number = { fg = palette.purple_soft or palette.red },
    Boolean = { fg = palette.purple_soft or palette.purple_medium or palette.red },
    Float = { fg = palette.purple_soft or palette.red },
    Identifier = { fg = palette.fg },
    Function = vim.tbl_extend("force", { fg = palette.yellow_soft or palette.yellow_muted or palette.orange_rust or palette.cyan }, opts.styles.functions),
    Operator = { fg = palette.orange_clay or palette.orange_rust or palette.yellow_muted or palette.yellow_gold or palette.medium_gray or palette.purple_muted or palette.fg },
    Type = vim.tbl_extend("force", { fg = palette.fg }, opts.styles.type),
    StorageClass = { fg = palette.carmine_bright or palette.gray_blue },
    Structure = { fg = palette.carmine_bright or palette.gray_blue },
    Typedef = { fg = palette.purple_muted or palette.fg },
    Keyword = vim.tbl_extend("force", { fg = palette.purple_muted or palette.orange_muted or palette.purple_soft or palette.gray_blue }, opts.styles.keywords),
    Statement = { fg = palette.purple_muted or palette.orange_muted or palette.purple_soft or palette.gray_blue },
    Conditional = { fg = palette.purple_muted or palette.orange_muted or palette.purple_soft or palette.gray_blue },
    Repeat = { fg = palette.purple_muted or palette.orange_muted or palette.purple_soft or palette.gray_blue },
    Label = { fg = palette.yellow_soft or palette.fg },
    Exception = { fg = palette.carmine_soft or palette.red },
    Include = { fg = palette.carmine_muted or palette.red },
    PreProc = { fg = palette.purple_muted or palette.fg },
    Define = { fg = palette.purple_soft or palette.red },
    Macro = { fg = palette.purple_medium or palette.cyan },
    PreCondit = { fg = palette.gray_warm or palette.medium_gray },
    Special = { fg = palette.yellow_soft or palette.fg },
    SpecialChar = { fg = palette.purple_medium or palette.medium_gray_blue },
    Tag = { fg = palette.yellow_soft or palette.blue },
    Debug = { fg = palette.yellow_warm or palette.red },
    Delimiter = { fg = palette.gray_warm or palette.fg },
    SpecialComment = vim.tbl_extend(
      "force",
      { fg = palette.medium_gray },
      opts.styles.comments
    ),
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = palette.cyan, bg = palette.bg, bold = true },
    Todo = { fg = palette.red, bg = palette.bg, bold = true },
    Error = { fg = palette.error, bg = palette.bg, bold = true },
    TabLine = { fg = palette.gray, bg = palette.alt_bg },
    TabLineSel = { fg = palette.fg, bg = palette.alt_bg },
    TabLineFill = { fg = palette.fg, bg = palette.alt_bg },
    WinSeparator = { fg = palette.medium_gray, bg = palette.bg },
    DiagnosticFloatingError = { fg = palette.error },
    FloatBorder = { fg = palette.light_gray },
  }
end

return M
