local M = {}

function M.highlight(palette, opts)
  return {
    ["@annotation"] = { fg = palette.yellow_gold or palette.fg },
    ["@attribute"] = { fg = palette.yellow_warm or palette.fg },
    ["@boolean"] = { fg = palette.purple_medium or palette.red },
    ["@character"] = { fg = palette.light_gray or palette.green },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = palette.gray_warm or palette.medium_gray },
    ["@comment.error"] = { fg = palette.error },
    ["@comment.note"] = { fg = palette.light_gray },
    ["@comment.todo"] = { fg = palette.yellow_neon or palette.todo },
    ["@comment.warning"] = { fg = palette.yellow_warm or palette.warning },
    ["@const.builtin"] = { fg = palette.purple_soft or palette.red },
    ["@const.macro"] = { fg = palette.purple_medium or palette.cyan },
    ["@constant"] = { fg = palette.fg },
    ["@constructor"] = { fg = palette.yellow_cream or palette.cyan },
    ["@constructor.python"] = { fg = palette.yellow_gold or palette.cyan },
    ["@diff.delta"] = {
      fg = palette.gray_blue,
      bg = palette.accent_blue,
      bold = true,
    },
    ["@error"] = { fg = palette.error },
    ["@field"] = { fg = palette.yellow_soft or palette.fg },
    ["@field.python"] = { fg = palette.yellow_pale or palette.fg },
    ["@function"] = vim.tbl_extend(
      "force",
      { fg = palette.yellow_cream or palette.cyan },
      opts.styles.functions
    ),
    ["@function.builtin"] = { fg = palette.purple_medium or palette.cyan },
    ["@function.macro"] = { fg = palette.purple_soft or palette.cyan },
    ["@function.method"] = { fg = palette.yellow_cream or palette.cyan },
    ["@function.method.call"] = { fg = palette.yellow_soft or palette.cyan },
    ["@keyword"] = vim.tbl_extend(
      "force",
      { fg = palette.purple_soft or palette.gray_blue },
      opts.styles.keywords
    ),
    ["@keyword.conditional"] = { fg = palette.purple_soft or palette.gray_blue },
    ["@keyword.coroutine"] = { fg = palette.purple_muted or palette.gray_blue },
    ["@keyword.exception"] = { fg = palette.purple_medium or palette.red },
    ["@keyword.function"] = vim.tbl_extend(
      "force",
      { fg = palette.purple_soft or palette.gray_blue },
      opts.styles.keywords
    ),
    ["@keyword.import"] = { fg = palette.purple_soft or palette.red },
    ["@keyword.operator"] = { fg = palette.purple_muted or palette.gray_blue },
    ["@keyword.repeat"] = { fg = palette.purple_soft or palette.gray_blue },
    ["@label"] = { fg = palette.yellow_soft or palette.fg },
    ["@lsp.type.comment"] = {},
    ["@markup"] = { fg = palette.fg },
    ["@markup.heading"] = { fg = palette.yellow_pale or palette.medium_gray },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = palette.yellow_pale or palette.medium_gray_blue },
    ["@markup.list"] = { fg = palette.yellow_soft or palette.fg },
    ["@markup.list.unchecked"] = { fg = palette.gray_warm or palette.fg },
    ["@markup.literal"] = { fg = palette.gray_warm or palette.medium_gray },
    ["@markup.strong"] = { fg = palette.medium_gray, bold = true },
    ["@markup.title"] = { fg = palette.yellow_pale or palette.medium_gray },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = palette.yellow_soft or palette.fg },
    ["@number"] = { fg = palette.purple_soft or palette.red },
    ["@number.float"] = { fg = palette.purple_soft or palette.red },
    ["@operator"] = { fg = palette.purple_muted or palette.fg },
    ["@property"] = { fg = palette.yellow_soft or palette.fg },
    ["@punctuation.bracket"] = { fg = palette.gray_warm or palette.fg },
    ["@punctuation.delimiter"] = { fg = palette.gray_warm or palette.fg },
    ["@string"] = { fg = palette.light_gray or palette.medium_gray_blue },
    ["@string.escape"] = { fg = palette.gray_warm or palette.medium_gray_blue },
    ["@string.regexp"] = { fg = palette.medium_gray or palette.medium_gray_blue },
    ["@string.special.path"] = { fg = palette.medium_gray or palette.light_gray },
    ["@string.special.symbol"] = { fg = palette.gray_warm or palette.medium_gray },
    ["@tag"] = { fg = palette.yellow_lightest or palette.blue },
    ["@tag.attribute"] = { fg = palette.yellow_soft or palette.fg },
    ["@tag.delimiter"] = { fg = palette.gray_warm or palette.fg },
    ["@text.literal"] = { fg = palette.gray_warm or palette.medium_gray },
    ["@text.reference"] = { fg = palette.yellow_pale or palette.light_gray },
    ["@text.strong"] = { bold = true },
    ["@text.emphasis"] = { italic = true },
    ["@text.uri"] = { fg = palette.yellow_pale or palette.light_gray, underline = true },
    ["@type"] = vim.tbl_extend("force", { fg = palette.fg }, opts.styles.type),
    ["@type.builtin"] = { fg = palette.purple_muted or palette.fg },
    ["@variable"] = vim.tbl_extend("force", { fg = palette.fg }, opts.styles.variables),
    ["@variable.builtin"] = { fg = palette.yellow_gold or palette.fg },
    ["@variable.builtin.python"] = { fg = palette.yellow_gold or palette.fg },
    ["@variable.field"] = { fg = palette.yellow_soft or palette.fg },
    ["@variable.member"] = { fg = palette.yellow_soft or palette.fg },
    ["@variable.parameter"] = { fg = palette.yellow_muted or palette.fg },
    ["@variable.parameter.reference"] = { fg = palette.yellow_muted or palette.fg },
  }
end

return M
